image:
- Visual Studio 2019
- macOS
- Ubuntu
 
skip_branch_with_pr: true
stack: python 3.11
 
environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX
 
install:
- pip install -r requirements.txt
 
build_script:
- flet pack pdfTreat.py --name PDF-TREAT --icon icon.png --product-name pdf-treat --product-version "1.2.3" --copyright "Copyright (c) 2024 MCDev3.0 Inc."
 
test: off
 
# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true
 
#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019
 
  after_build:
  - 7z a pdf-treat.zip %CD%\dist\*.exe
 
  artifacts:
  - path: pdf-treat.zip
 
#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS
 
  after_build:
  - tar -czvf pdf-treat-macos.tar.gz -C dist pdf-treat.app
 
  artifacts:
  - path: pdf-treat-macos.tar.gz
 
#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu
 
  after_build:
  - tar -czvf pdf-treat-linux.tar.gz -C dist pdf-treat
 
  artifacts:
  - path: pdf-treat-linux.tar.gz